/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSmartPricingRouteImport } from './routes/app.smart-pricing'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPropertiesCalendarRouteImport } from './routes/app.properties-calendar'
import { Route as AppPropertiesAnalyticsRouteImport } from './routes/app.properties-analytics'
import { Route as AppPropertiesRouteImport } from './routes/app.properties'
import { Route as AppOwnerRouteImport } from './routes/app.owner'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppInvestorRouteImport } from './routes/app.investor'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppContractsRouteImport } from './routes/app.contracts'
import { Route as AppComingSoonRouteImport } from './routes/app.coming-soon'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppPropertiesIdRouteImport } from './routes/app.properties.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSmartPricingRoute = AppSmartPricingRouteImport.update({
  id: '/smart-pricing',
  path: '/smart-pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesCalendarRoute = AppPropertiesCalendarRouteImport.update({
  id: '/properties-calendar',
  path: '/properties-calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesAnalyticsRoute = AppPropertiesAnalyticsRouteImport.update({
  id: '/properties-analytics',
  path: '/properties-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerRoute = AppOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorRoute = AppInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppComingSoonRoute = AppComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPropertiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/coming-soon': typeof AppComingSoonRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/properties-analytics': typeof AppPropertiesAnalyticsRoute
  '/app/properties-calendar': typeof AppPropertiesCalendarRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/smart-pricing': typeof AppSmartPricingRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/coming-soon': typeof AppComingSoonRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/properties-analytics': typeof AppPropertiesAnalyticsRoute
  '/app/properties-calendar': typeof AppPropertiesCalendarRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/smart-pricing': typeof AppSmartPricingRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai': typeof AppAiRoute
  '/app/coming-soon': typeof AppComingSoonRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/properties': typeof AppPropertiesRouteWithChildren
  '/app/properties-analytics': typeof AppPropertiesAnalyticsRoute
  '/app/properties-calendar': typeof AppPropertiesCalendarRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/smart-pricing': typeof AppSmartPricingRoute
  '/app/properties/$id': typeof AppPropertiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/ai'
    | '/app/coming-soon'
    | '/app/contracts'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/investor'
    | '/app/marketplace'
    | '/app/owner'
    | '/app/properties'
    | '/app/properties-analytics'
    | '/app/properties-calendar'
    | '/app/settings'
    | '/app/smart-pricing'
    | '/app/properties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/ai'
    | '/app/coming-soon'
    | '/app/contracts'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/investor'
    | '/app/marketplace'
    | '/app/owner'
    | '/app/properties'
    | '/app/properties-analytics'
    | '/app/properties-calendar'
    | '/app/settings'
    | '/app/smart-pricing'
    | '/app/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/ai'
    | '/app/coming-soon'
    | '/app/contracts'
    | '/app/crm'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/investor'
    | '/app/marketplace'
    | '/app/owner'
    | '/app/properties'
    | '/app/properties-analytics'
    | '/app/properties-calendar'
    | '/app/settings'
    | '/app/smart-pricing'
    | '/app/properties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/smart-pricing': {
      id: '/app/smart-pricing'
      path: '/smart-pricing'
      fullPath: '/app/smart-pricing'
      preLoaderRoute: typeof AppSmartPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties-calendar': {
      id: '/app/properties-calendar'
      path: '/properties-calendar'
      fullPath: '/app/properties-calendar'
      preLoaderRoute: typeof AppPropertiesCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties-analytics': {
      id: '/app/properties-analytics'
      path: '/properties-analytics'
      fullPath: '/app/properties-analytics'
      preLoaderRoute: typeof AppPropertiesAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/owner': {
      id: '/app/owner'
      path: '/owner'
      fullPath: '/app/owner'
      preLoaderRoute: typeof AppOwnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor': {
      id: '/app/investor'
      path: '/investor'
      fullPath: '/app/investor'
      preLoaderRoute: typeof AppInvestorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contracts': {
      id: '/app/contracts'
      path: '/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coming-soon': {
      id: '/app/coming-soon'
      path: '/coming-soon'
      fullPath: '/app/coming-soon'
      preLoaderRoute: typeof AppComingSoonRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties/$id': {
      id: '/app/properties/$id'
      path: '/$id'
      fullPath: '/app/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppPropertiesRoute
    }
  }
}

interface AppPropertiesRouteChildren {
  AppPropertiesIdRoute: typeof AppPropertiesIdRoute
}

const AppPropertiesRouteChildren: AppPropertiesRouteChildren = {
  AppPropertiesIdRoute: AppPropertiesIdRoute,
}

const AppPropertiesRouteWithChildren = AppPropertiesRoute._addFileChildren(
  AppPropertiesRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppComingSoonRoute: typeof AppComingSoonRoute
  AppContractsRoute: typeof AppContractsRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppInvestorRoute: typeof AppInvestorRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppOwnerRoute: typeof AppOwnerRoute
  AppPropertiesRoute: typeof AppPropertiesRouteWithChildren
  AppPropertiesAnalyticsRoute: typeof AppPropertiesAnalyticsRoute
  AppPropertiesCalendarRoute: typeof AppPropertiesCalendarRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmartPricingRoute: typeof AppSmartPricingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppComingSoonRoute: AppComingSoonRoute,
  AppContractsRoute: AppContractsRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppInvestorRoute: AppInvestorRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppOwnerRoute: AppOwnerRoute,
  AppPropertiesRoute: AppPropertiesRouteWithChildren,
  AppPropertiesAnalyticsRoute: AppPropertiesAnalyticsRoute,
  AppPropertiesCalendarRoute: AppPropertiesCalendarRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSmartPricingRoute: AppSmartPricingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
